baseURL: "https://jiajunmao.github.io/" 
title: Jiajun Mao
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 1
        - name: Projects
          url: projects/
          weight: 2
        - name: Blogs
          url: blogs/
          weight: 3
        - name: Tags
          url: tags/
          weight: 4

params:
    description: "I am currently a joint BS/MS computer science student at **University of Chicago** with **computer systems** concentration. My research area lies in improving reliability, 
          efficiency and performance of storage systems through novel erasure coding schemes and placement schemes.<br/><br/>
          
          I am a member of [UChicago systems research on Availability, Reliability and Efficiency(UCARE)](https://ucare.cs.uchicago.edu/) where I am fortunate to be advised by [**Professor Haryadi Gunawi**](http://people.cs.uchicago.edu/~haryadi/)."
    author: Name
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: "Nihao<span style='font-size: 15px'>(你好)</span>, This is Jiajun Mao<span style='font-size: 15px'>(毛嘉骏)</span>"
          subtitle: "I am currently a joint BS/MS computer science student at **University of Chicago** with **computer systems** concentration. My research area lies in improving reliability, 
          efficiency and performance of storage systems through novel erasure coding schemes, placement schemes, and machine learning.<br/><br/>
          

          I am a member of [UChicago systems research on Availability, Reliability and Efficiency(UCARE)](https://ucare.cs.uchicago.edu/) where I am fortunate to be advised by [**Professor Haryadi Gunawi**](http://people.cs.uchicago.edu/~haryadi/).<br/><br/>

          During my free time, I enjoy the company of my two cats, who are **the cutest** in the world. I also love to cook, though different people might have different regards on how good they are :)
          <br/><br/>"
          imageUrl: "picture.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Jiajun Mao
          buttons:
            - name: Papers
              url: papers/
            - name: Projects
              url: projects/
            # - name: Newsletter
            #   url: https://pmichaillat.substack.com
            # - name: Tags
            #   url: tags/
            - name: Blogs
              url: blogs/
            - name: Tags
              url: tags/
            - name: My Cats 😺
              url: https://images.naturecraft.world/album/cats.Xrv
    socialIcons:
        - name: CV
          url: CV2023-12.pdf
        - name: Email
          url: mailto:jiajunm@uchicago.edu
        # - name: Location
        #   url: location/
        # - name: Office Hours
        #   url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=7-MV8MgAAAAJ
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat
        - name: GitHub
          url: https://github.com/jiajunmao
        - name: LinkedIn
          url: https://www.linkedin.com/in/jiajun-mao/
        # - name: Twitter
        #   url: https://twitter.com/pmichaillat

    assets:
        disableHLJS: true
        disableScrollBarStyle: false
        favicon: favicon.ico
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Jiajun Mao"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
